### ISSUE TITLE
issue of running "all"

### ISSUE THREAD

**Issue by yangwukaidi** [EwenBurban/RIDGE#2]
Hi
Sorry, I have a new issue with running "bash RIDGE. sh  config. yaml all".
The error is as follows，
_[100000 rows x 23 columns]
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 5120 current, 5120 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 5120 current, 5120 max_
_..._
_Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.9 from "/usr/local/bin/python3"
  * The NumPy version is: "1.26.4"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: PyCapsule_Import could not import module "datetime"
The above exception was the direct cause of the following exception:_
_Traceback (most recent call last):
  File "/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/core/scrm_calc.py", line 1, in <module>
    import allel
  File "/usr/local/lib/python3.9/site-packages/allel/__init__.py", line 4, in <module>
    from .model.ndarray import *
  File "/usr/local/lib/python3.9/site-packages/allel/model/ndarray.py", line 7, in <module>
    import numpy as np
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Segmentation fault
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 5120 current, 5120 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 5120 current, 5120 max_
_..._
_...
Error in job simulation_locus while creating output files /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus/ABCstat_locus.txt, /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus/priorfile_locus.txt.
RuleException:
CalledProcessError in line 242 of /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/core/RIDGE_pipeline.py:
Command '
        mkdir -p /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus
        cd /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus
        singularity exec --bind /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE,/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/container/python.sif python3 /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/core/submit_priorgen_locus.py              locus_datafile=/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/locus_datafile             config_yaml=/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/config.yaml binpath=/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/core nMultilocus=1000 priorfile=/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/posterior.txt locus_write=True global_write=False Nref=95000
        split exec.sh -l5 sub_exec
        list_sub=(sub_exec*)
        for sub in ${list_sub[@]}; do echo sh $sub >> tmp_exec.sh; done
        singularity exec --bind /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE,/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/container/scrm_py.sif parallel -a tmp_exec.sh
        rm tmp_exec.sh sub_exec* exec.sh
        sed -i '2,${/dataset/d}' ABCstat_locus.txt
        ' returned non-zero exit status 69.
  File "/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/core/RIDGE_pipeline.py", line 242, in __rule_simulation_locus
  File "/home/user/anaconda3/envs/snakemake_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job simulation_locus since they might be corrupted:
/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus/ABCstat_locus.txt, /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/test/sim_locus/priorfile_locus.txt
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message_

I originally thought that my computing resources were insufficient to cause this issue, but I wrote ntask_load=140 to launch_param.sh and still got a similar error.
I put the complete error in the attachment, I hope you can check it.
How can I resolve this issue？
Best.
[20240408.log](https://github.com/EwenBurban/RIDGE/files/14906633/20240408.log)

**Comment by yangwukaidi** [comment]
Hi,
Because I only have 24 CPUs, so I write ntask_load=4 in launch_param.sh and it runs successfully.
Based on my current computing resources, what's the maximum ntask_load can be set to?

**Comment by EwenBurban** [comment]
Hi,
Thanks for your interesting returns. It help me to improve RIDGE. 
Actually, you could theoretically try to set up ntask_load=6 (which is the theoritical maximum that your computer can support as the maximum of CPU required by a  tasks in RIDGE is  4 CPU, so 6*4=24) .
But i’m suprised by the behavior of snakemake, because it supposed to take in account the ressources of your computer.
I’ll try to improve RIDGE to avoid this types of behavior. I keep this issue open util then.
Best

**Comment by yangwukaidi** [comment]
Thanks for your reply.
I recently had preliminary results. 
I define prior bounds based on prior_bound_suggestion.txt. The results of running "test" and "all" in QC_plot as follows.
![1](https://github.com/EwenBurban/RIDGE/assets/127917612/0685b961-eaec-4005-b685-7ce5addf7845)
![2](https://github.com/EwenBurban/RIDGE/assets/127917612/694e4df7-9e59-4fd0-94e3-70e1102a13c9)
Based on this result, are my prior bounds appropriate?
If not, how to adjust it?
Config.yaml  file is attached. Please receive it.
Best wishes to you.

**Comment by EwenBurban** [comment]
Hi !
I didn’t foud the config.yaml file but from what I see, everything is good except migration (M_max and eventually M_min) that I suggest you to increases because your obs is completely out of the ss_avg prior and posterior distribution.
Best

**Comment by yangwukaidi** [comment]
Sorry, the last upload may not succeed. 
The following is the config.yaml file.

config_yaml: config.yaml
vcf_file: 12.vcf
contig_data: contig_data.txt
rec_rate_map: NA
popfile: 12.csv
nameA: Z
nameB: QBZ
container_path: /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/container
ploidy: 2
lightMode: True
work_dir: /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/RIDGE/12
nLoci: 1000
window_size: 20000
homo_rec: True
homo_rec_rate: 1.5e-8
mu: 2.5e-8
Nref: 48592
M_max: 50
M_min: 0.1
N_max: 91785
N_min: 5400
Tsplit_min: 400
Tsplit_max: 88816
Pbarrier_max: 0.2
hetero_theta: False

I will follow your advice to adjust, or are there other parameters that need to be adjusted?
Best wishes to you.

**Comment by yangwukaidi** [comment]
Hi.
I tried to increase M_min and M_max to 10x, 20x, 100x, but that didn't solve the problem, and the obs of SS_avg was still outside the priori. This is a really troubling problem. 
Best wishes to you.

**Comment by EwenBurban** [comment]
Hi ! 
Sorry for the delay, I’m still sick.
After reviewing your results, Maybe you can try to reduce the T_split_max, which appear to be very hight relatively to your level of netDiv_avg. This also could explain the lower SS_avg in prior (as Tsplit decreases, ss increases, that’s not linear but it could be an explanation).
Best
